version: "3"
services:
  yumi:
    build: .
    image: yumi
    volumes:
      - .:/root/workspace
      - /tmp/.X11-unix:/tmp/.X11-unix
    stdin_open: true 
    tty: true
    environment:
      - DISPLAY=${DISPLAY}
    network_mode: host
